Dir(['docker-hadoop',
     'docker-hive',
     'docker-hive-metastore-postgresql',
     'docker-spark',
     'docker-kafka',
     'docker-command',
     'docker-zeppelin',
     'docker-kafka',
     'docker-minio',
     'docker-postgres',
     'docker-airflow',
     'docker-elastic',
     'docker-nifi'],
     name="labtools")

